language: python

env:
- MOD1="plusser"
- MOD2="yamler"

python:
- '2.7'

cache: pip

install:
- pip install -r reqs/dev.txt
- pip install -r reqs/run.txt

script:
- pylint $MOD1
- pylint $MOD2
- flake8 $MOD1 $MOD2 --count
#- coverage run --source $MOD -m py.test -vs
#- coverage report --fail-under=70 -m

branches:
  only:
  - master

notifications:
  slack:
    on_success: never
    on_failure: change
    secure: ???
